import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  HydrationBoundary,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";
import ReactQueryProvider from "./utils/provider/reactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={inter.className} suppressHydrationWarning={true}>
          {children}
        </body>
      </ReactQueryProvider>
    </html>
  );
}
